/* eslint-disable */
/* biome-ignore-all */
/* stylelint-disable */
/* editorconfig-checker-disable-file */
/* oxlint-disable */
/* oxcformat-ignore */
/**
 * 标题：xw-client_接口文档 - version 版本号:1.0.0
 *
 * 描述：xw-client接口文档
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://worma.js.org
 *
 * **Do not edit the file manually.**
 */
/// <reference types='./globals.d.ts' />

const apiDefinitions = {
  'contactNote.list': ['GET', '/contact-note/contact/{contactId}'],
  'contactNote.create': ['POST', '/contact-note/create'],
  'contactNote.getDetail': ['GET', '/contact-note/{id}'],
  'contactNote.update': ['PUT', '/contact-note/{id}'],
  'contactNote.delete': ['DELETE', '/contact-note/{id}'],
  'contactNoteContact.createCall': ['POST', '/contact-note/contact/{contactId}/call'],
  'contactNoteContact.page': ['GET', '/contact-note/contact/{contactId}/page'],
  'contactNoteContact.createSms': ['POST', '/contact-note/contact/{contactId}/sms'],
  'contact.createContact': ['POST', '/contact/create'],
  'contact.getContacts': ['GET', '/contact/list'],
  'contact.getContactsByNotebook': ['GET', '/contact/notebook/{notebookId}'],
  'contact.listSearchHistory': ['GET', '/contact/search-history'],
  'contact.clearSearchHistory': ['DELETE', '/contact/search-history'],
  'contact.getContact': ['GET', '/contact/{id}'],
  'contact.updateContact': ['PUT', '/contact/{id}'],
  'contact.deleteContact': ['DELETE', '/contact/{id}'],
  'contact.setFollowStatus': ['PUT', '/contact/{id}/follow'],
  'contact.moveToNotebook': ['PUT', '/contact/{id}/notebook'],
  'contact.getContactOverview': ['GET', '/contact/{id}/overview'],
  'contactNotebook.batchImport': ['POST', '/contact/notebook/{notebookId}/batch-import'],
  'contactNotebook.getDisplaySetting': ['GET', '/contact/notebook/{notebookId}/display-settings'],
  'contactNotebook.saveDisplaySetting': ['PUT', '/contact/notebook/{notebookId}/display-settings'],
  'contactNotebook.findImportedPhones': ['POST', '/contact/notebook/{notebookId}/imported-check'],
  'contactNotebook.pageContacts': ['GET', '/contact/notebook/{notebookId}/page'],
  'contactNotebook.getContactStatistics': ['GET', '/contact/notebook/{notebookId}/stats'],
  'contactRelation.create': ['POST', '/contact/{contactId}/relation/create'],
  'contactRelation.delete': ['DELETE', '/contact/{contactId}/relation/delete/{id}'],
  'contactRelation.list': ['GET', '/contact/{contactId}/relation/list'],
  'contactRelation.update': ['PUT', '/contact/{contactId}/relation/update/{id}'],
  'contactTag.create': ['POST', '/contact/{contactId}/tag/create'],
  'contactTag.delete': ['DELETE', '/contact/{contactId}/tag/delete/{id}'],
  'contactTag.list': ['GET', '/contact/{contactId}/tag/list'],
  'contactTag.update': ['PUT', '/contact/{contactId}/tag/update/{id}'],
  'district.list': ['GET', '/district/list'],
  'district.getDistrictTree': ['GET', '/district/tree'],
  'file.uploadToken': ['GET', '/file/token'],
  'file.uploadFile': ['POST', '/file/upload'],
  'financeRecord.create': ['POST', '/finance-record/create'],
  'financeRecord.list': ['GET', '/finance-record/notebook/{notebookId}'],
  'financeRecord.getDetail': ['GET', '/finance-record/{id}'],
  'financeRecord.update': ['PUT', '/finance-record/{id}'],
  'financeRecord.delete': ['DELETE', '/finance-record/{id}'],
  'financeRecordNotebook.page': ['GET', '/finance-record/notebook/{notebookId}/page'],
  'financeType.create': ['POST', '/finance-type/create'],
  'financeType.list': ['GET', '/finance-type/list'],
  'financeType.update': ['PUT', '/finance-type/{id}'],
  'financeType.delete': ['DELETE', '/finance-type/{id}'],
  'gate.login': ['POST', '/gate/login'],
  'gate.phoneVerificationCode': ['POST', '/gate/phoneVerification'],
  'notebook.createNotebook': ['POST', '/notebook/create'],
  'notebook.getNotebooks': ['GET', '/notebook/list'],
  'notebook.updateNotebook': ['PUT', '/notebook/{id}'],
  'notebook.deleteNotebook': ['DELETE', '/notebook/{id}'],
  'notebook.setDefaultNotebook': ['PUT', '/notebook/{id}/default'],
  'purchaser.setAvatar': ['GET', '/purchaser/avatar'],
  'purchaser.setBirthday': ['POST', '/purchaser/birthday'],
  'purchaser.current': ['GET', '/purchaser/current'],
  'purchaser.setNickname': ['POST', '/purchaser/nickname'],
  'purchaser.setPassword': ['POST', '/purchaser/set/password'],
  'purchaser.setSex': ['GET', '/purchaser/sex'],
  'purchaser.updatePassword': ['POST', '/purchaser/update/password'],
  'purchaser.changePhone': ['POST', '/purchaser/updatePhone'],
  'purchaser.validUpdatePhone': ['POST', '/purchaser/valid/updatePhone']
};

export default apiDefinitions;
