/* eslint-disable */
/* biome-ignore-all */
/* stylelint-disable */
/* editorconfig-checker-disable-file */
/* oxlint-disable */
/* oxcformat-ignore */
/**
 * 标题：xw-client_接口文档 - version 版本号:1.0.0
 *
 * 描述：xw-client接口文档
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://worma.js.org
 *
 * **Do not edit the file manually.**
 */
/// <reference types='./globals.d.ts' />

const apiDefinitions = {
  'contact.getContacts': ['GET', '/contact'],
  'contact.createContact': ['POST', '/contact'],
  'contact.getContactsByNotebook': ['GET', '/contact/notebook/{notebookId}'],
  'contact.pageContacts': ['GET', '/contact/notebook/{notebookId}/page'],
  'contact.getContact': ['GET', '/contact/{id}'],
  'contact.updateContact': ['PUT', '/contact/{id}'],
  'contact.deleteContact': ['DELETE', '/contact/{id}'],
  'contact.setFollowStatus': ['PUT', '/contact/{id}/follow'],
  'contact.getContactOverview': ['GET', '/contact/{id}/overview'],
  'contactNote.create': ['POST', '/contact-note'],
  'contactNote.list': ['GET', '/contact-note/contact/{contactId}'],
  'district.list': ['GET', '/district/list'],
  'district.getDistrictTree': ['GET', '/district/tree'],
  'file.uploadToken': ['GET', '/file/token'],
  'file.uploadFile': ['POST', '/file/upload'],
  'financeRecord.create': ['POST', '/finance-record'],
  'financeRecord.list': ['GET', '/finance-record/notebook/{notebookId}'],
  'financeRecord.page': ['GET', '/finance-record/notebook/{notebookId}/page'],
  'financeRecord.getDetail': ['GET', '/finance-record/{id}'],
  'financeRecord.update': ['PUT', '/finance-record/{id}'],
  'financeRecord.delete': ['DELETE', '/finance-record/{id}'],
  'financeType.list': ['GET', '/finance-type'],
  'financeType.create': ['POST', '/finance-type'],
  'financeType.update': ['PUT', '/finance-type/{id}'],
  'financeType.delete': ['DELETE', '/finance-type/{id}'],
  'gate.login': ['POST', '/gate/login'],
  'gate.phoneVerificationCode': ['POST', '/gate/phoneVerification'],
  'notebook.getNotebooks': ['GET', '/notebook'],
  'notebook.createNotebook': ['POST', '/notebook'],
  'notebook.updateNotebook': ['PUT', '/notebook/{id}'],
  'notebook.deleteNotebook': ['DELETE', '/notebook/{id}'],
  'notebook.setDefaultNotebook': ['PUT', '/notebook/{id}/default'],
  'purchaser.setAvatar': ['GET', '/purchaser/avatar'],
  'purchaser.setBirthday': ['POST', '/purchaser/birthday'],
  'purchaser.setNickname': ['POST', '/purchaser/nickname'],
  'purchaser.setPassword': ['POST', '/purchaser/set/password'],
  'purchaser.setSex': ['GET', '/purchaser/sex'],
  'purchaser.updatePassword': ['POST', '/purchaser/update/password'],
  'purchaser.changePhone': ['POST', '/purchaser/updatePhone'],
  'purchaser.validUpdatePhone': ['POST', '/purchaser/valid/updatePhone']
};

export default apiDefinitions;
