/* eslint-disable */
/* biome-ignore-all */
/* stylelint-disable */
/* editorconfig-checker-disable-file */
/* oxlint-disable */
/* oxcformat-ignore */
/**
 * 标题：xw-client_接口文档 - version 版本号:1.0.0
 *
 * 描述：xw-client接口文档
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://worma.js.org
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { alovaInstance, $$userConfigMap } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;

type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface _ {
  /**
   * 区域树
   */

  children?: _[];
  /**
   * 区域代码
   */

  districtCode?: string;
  /**
   * 区域ID
   */

  districtId?: number;
  /**
   * 区域名称
   */

  districtName?: string;
  /**
   * 区域父级
   */

  districtParentId?: number;
}
export interface _2 {
  /**
   * 电话号码
   */

  phone: string;
  /**
   * 密钥 secret规则: 6位随机数 + MD5(phone+type+ORIGIN_SECRET) + millis（13位） + 6位随机数
   */

  secret: string;
  /**
   * 验证码类型 登录：0
   */

  type: string;
  valid?: boolean;
}
export interface _3 {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * 响应内容
   */

  data?: object;
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _4 {
  /**
   * 验证码
   */

  code?: string;
  /**
   * 电话号码
   */

  phone?: string;
}
export interface _5 {
  /**
   * 验证码
   */

  code?: string;
  /**
   * 密码
   */

  password?: string;
  /**
   * 电话号码
   */

  phone: string;
  /**
   * 登录类型:1验证码2密码
   */

  type: string;
}
export interface _ContactNoteResponseDTO_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * ContactNoteResponseDTO
   * ---
   * 跟进记事响应数据
   */

  data?: ContactNoteResponseDTO;
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _ContactOverviewResponseDTO_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * ContactOverviewResponseDTO
   * ---
   * 联系人详情聚合响应数据
   */

  data?: ContactOverviewResponseDTO;
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _ContactPageResponseDTO_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * ContactPageResponseDTO
   * ---
   * 人脉分页查询响应数据
   */

  data?: ContactPageResponseDTO;
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _ContactResponseDTO_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * ContactResponseDTO
   * ---
   * 联系人响应DTO
   */

  data?: ContactResponseDTO;
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _DTO {
  /**
   * 新密码
   */

  newPassword: string;
  /**
   * 原密码
   */

  oldPassword: string;
}
export interface _DTO2 {
  /**
   * 生日
   */

  birthday: string;
}
export interface _FinanceRecordPageResponseDTO_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * FinanceRecordPageResponseDTO
   * ---
   * 收支记录分页响应数据
   */

  data?: FinanceRecordPageResponseDTO;
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _FinanceRecordResponseDTO_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * FinanceRecordResponseDTO
   * ---
   * 收支记录响应数据
   */

  data?: FinanceRecordResponseDTO;
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _FinanceTypeResponseDTO_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * FinanceTypeResponseDTO
   * ---
   * 收支类型响应数据
   */

  data?: FinanceTypeResponseDTO;
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _HashMap_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * 响应内容
   */

  data?: Record<string, object>;
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _List_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * 响应内容
   */

  data?: _[];
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _List_ContactNoteResponseDTO_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * 响应内容
   */

  data?: ContactNoteResponseDTO[];
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _List_ContactResponseDTO_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * 响应内容
   */

  data?: ContactResponseDTO[];
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _List_DistrictLevelDto_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * 响应内容
   */

  data?: DistrictLevelDto[];
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _List_FinanceRecordResponseDTO_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * 响应内容
   */

  data?: FinanceRecordResponseDTO[];
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _List_FinanceTypeResponseDTO_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * 响应内容
   */

  data?: FinanceTypeResponseDTO[];
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _List_NotebookResponseDTO_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * 响应内容
   */

  data?: NotebookResponseDTO[];
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _NotebookResponseDTO_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * NotebookResponseDTO
   * ---
   * 记事本响应数据
   */

  data?: NotebookResponseDTO;
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _PurchaserResponseDTO_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * PurchaserResponseDTO
   * ---
   * 当前用户响应数据
   */

  data?: PurchaserResponseDTO;
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _string_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * 响应内容
   */

  data?: string;
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _token {
  /**
   * 上传Token
   */

  token?: string;
}
export interface _token_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * 生成token
   * ---
   */

  data?: _token;
  /**
   * 响应消息
   */

  msg?: string;
}
export interface _Void_ {
  /**
   * 响应业务码
   */

  code?: number;
  /**
   * 响应消息
   */

  msg?: string;
}
export interface ContactDTO {
  /**
   * 生日日期
   */

  birthday?: string;
  /**
   * 公司地址
   */

  companyAddress?: string;
  /**
   * 公司名称
   */

  companyName?: string;
  /**
   * 部门
   */

  department?: string;
  /**
   * 家庭地址
   */

  homeAddress?: string;
  /**
   * 是否关注
   */

  isFollow?: boolean;
  /**
   * 联系人姓名
   */

  name: string;
  /**
   * 记事本ID
   */

  notebookId: number;
  /**
   * 联系电话列表
   */

  phones?: ContactPhoneDTO[];
  /**
   * 职位
   */

  position?: string;
  /**
   * 性别
   */

  sex?: string;
  /**
   * 来源
   */

  source?: string;
}
export interface ContactFinanceStatsDTO {
  /**
   * 差额，成交总额减支出总额
   */

  balance?: number;
  /**
   * 成交总额，不含退款
   */

  dealAmount?: number;
  /**
   * 成交记录数量，不含退款
   */

  dealCount?: number;
  /**
   * 支出总额，不含退款
   */

  expenseAmount?: number;
  /**
   * 支出记录数量，不含退款
   */

  expenseCount?: number;
}
export interface ContactListStatsDTO {
  /**
   * 产生成交的联系人数量
   */

  dealContacts?: number;
  /**
   * 产生支出的联系人数量
   */

  expenseContacts?: number;
  /**
   * 新增人脉数量
   */

  newContacts?: number;
}
export interface ContactNoteDTO {
  /**
   * 通话时长，单位：秒
   */

  callDuration?: number;
  /**
   * 通话类型：in-呼入，out-呼出
   */

  callType?: string;
  /**
   * 联系人ID
   */

  contactId: number;
  /**
   * 记事内容
   */

  content?: string;
  /**
   * 事件发生时间，格式：yyyy-MM-dd HH:mm:ss
   */

  eventTime?: string;
  /**
   * 拜访纬度
   */

  lat?: number;
  /**
   * 拜访经度
   */

  lng?: number;
  /**
   * 记事类型：call-电话联系，sms-短信联系，normal-普通记事，visit-拜访记事
   */

  noteType: string;
  /**
   * 记事本ID
   */

  notebookId: number;
  /**
   * 联系电话
   */

  phone?: string;
  /**
   * 短信类型：in-接收，out-发送
   */

  smsType?: string;
  /**
   * 拜访地址
   */

  visitAddress?: string;
}
export interface ContactNoteResponseDTO {
  /**
   * 通话时长，单位：秒
   */

  callDuration?: number;
  /**
   * 通话类型
   */

  callType?: string;
  /**
   * 联系人ID
   */

  contactId?: number;
  /**
   * 记事内容
   */

  content?: string;
  /**
   * 创建时间，格式：yyyy-MM-dd HH:mm:ss
   */

  createTime?: string;
  /**
   * 事件发生时间，格式：yyyy-MM-dd HH:mm:ss
   */

  eventTime?: string;
  /**
   * 跟进记事ID
   */

  id?: number;
  /**
   * 拜访纬度
   */

  lat?: number;
  /**
   * 拜访经度
   */

  lng?: number;
  /**
   * 更新时间，格式：yyyy-MM-dd HH:mm:ss
   */

  modifyTime?: string;
  /**
   * 记事类型：call-电话联系，sms-短信联系，normal-普通记事，visit-拜访记事
   */

  noteType?: string;
  /**
   * 记事本ID
   */

  notebookId?: number;
  /**
   * 联系电话
   */

  phone?: string;
  /**
   * 短信类型
   */

  smsType?: string;
  /**
   * 拜访地址
   */

  visitAddress?: string;
}
export interface ContactOverviewResponseDTO {
  /**
   * ContactResponseDTO
   * ---
   * 联系人响应DTO
   */

  contact?: ContactResponseDTO;
  /**
   * 联系人收支记录
   */

  financeRecords?: FinanceRecordResponseDTO[];
  /**
   * ContactFinanceStatsDTO
   * ---
   * 联系人收支统计数据
   */

  financeStats?: ContactFinanceStatsDTO;
  /**
   * 最近十条跟进记事
   */

  recentNotes?: ContactNoteResponseDTO[];
}
export interface ContactPageResponseDTO {
  /**
   * 当前页码，从1开始
   */

  pageNo?: number;
  /**
   * 每页数量
   */

  pageSize?: number;
  /**
   * 当前页数据
   */

  records?: ContactResponseDTO[];
  /**
   * ContactListStatsDTO
   * ---
   * 人脉列表统计数据
   */

  stats?: ContactListStatsDTO;
  /**
   * 总记录数
   */

  total?: number;
}
export interface ContactPhoneDTO {
  /**
   * 联系电话
   */

  phone?: string;
  /**
   * 电话类型
   */

  type?: string;
}
export interface ContactResponseDTO {
  /**
   * 生日
   */

  birthday?: string;
  /**
   * 公司地址
   */

  companyAddress?: string;
  /**
   * 公司名称
   */

  companyName?: string;
  /**
   * 创建时间
   */

  createTime?: string;
  /**
   * 部门
   */

  department?: string;
  /**
   * 家庭地址
   */

  homeAddress?: string;
  /**
   * 联系人ID
   */

  id?: number;
  /**
   * 是否关注
   */

  isFollow?: boolean;
  /**
   * 更新时间
   */

  modifyTime?: string;
  /**
   * 联系人姓名
   */

  name?: string;
  /**
   * 记事本ID
   */

  notebookId?: number;
  /**
   * 联系电话列表
   */

  phones?: ContactPhoneDTO[];
  /**
   * 职位
   */

  position?: string;
  /**
   * 性别
   */

  sex?: string;
  /**
   * 来源
   */

  source?: string;
}
export interface DistrictLevelDto {
  /**
   * 行政区划代码
   */

  code?: string;
  /**
   * 行政区
   */

  district?: string;
  id?: number;
  /**
   * 级别
   */

  level?: number;
  /**
   * 下级行政区列表
   */

  list?: DistrictLevelDto[];
  /**
   * 父级id
   */

  parentId?: number;
}
export interface FinanceRecordDTO {
  /**
   * 金额，必须大于0
   */

  amount: number;
  /**
   * 收支分类：成交、支出
   */

  category: string;
  /**
   * 联系人ID，可为空
   */

  contactId?: number;
  /**
   * 发生时间，格式：yyyy-MM-dd HH:mm:ss
   */

  eventTime?: string;
  /**
   * 是否退款，退款记录不计入统计
   */

  isRefund?: boolean;
  /**
   * 记事本ID
   */

  notebookId: number;
  /**
   * 备注
   */

  remark?: string;
  /**
   * 收支类型ID
   */

  typeId?: number;
}
export interface FinanceRecordPageResponseDTO {
  /**
   * 当前页码，从1开始
   */

  pageNo?: number;
  /**
   * 每页数量
   */

  pageSize?: number;
  /**
   * 当前页数据
   */

  records?: FinanceRecordResponseDTO[];
  /**
   * 总记录数
   */

  total?: number;
}
export interface FinanceRecordResponseDTO {
  /**
   * 金额
   */

  amount?: number;
  /**
   * 收支分类：成交、支出
   */

  category?: string;
  /**
   * 联系人ID
   */

  contactId?: number;
  /**
   * 创建时间，格式：yyyy-MM-dd HH:mm:ss
   */

  createTime?: string;
  /**
   * 发生时间，格式：yyyy-MM-dd HH:mm:ss
   */

  eventTime?: string;
  /**
   * 收支记录ID
   */

  id?: number;
  /**
   * 是否退款
   */

  isRefund?: boolean;
  /**
   * 更新时间，格式：yyyy-MM-dd HH:mm:ss
   */

  modifyTime?: string;
  /**
   * 记事本ID
   */

  notebookId?: number;
  /**
   * 备注
   */

  remark?: string;
  /**
   * 收支类型ID
   */

  typeId?: number;
  /**
   * 收支类型名称
   */

  typeName?: string;
}
export interface FinanceTypeDTO {
  /**
   * 排序号
   */

  sortNo?: number;
  /**
   * 类型分类：成交、支出
   */

  typeCategory: string;
  /**
   * 类型名称
   */

  typeName: string;
}
export interface FinanceTypeResponseDTO {
  /**
   * 创建时间，格式：yyyy-MM-dd HH:mm:ss
   */

  createTime?: string;
  /**
   * 类型ID
   */

  id?: number;
  /**
   * 更新时间，格式：yyyy-MM-dd HH:mm:ss
   */

  modifyTime?: string;
  /**
   * 排序号
   */

  sortNo?: number;
  /**
   * 类型分类：成交、支出
   */

  typeCategory?: string;
  /**
   * 类型名称
   */

  typeName?: string;
}
export interface NotebookDTO {
  /**
   * 记事本名称
   */

  name: string;
  /**
   * 排序号
   */

  sortNo?: number;
}
export interface NotebookResponseDTO {
  /**
   * 创建时间
   */

  createTime?: string;
  /**
   * 记事本ID
   */

  id?: number;
  /**
   * 是否默认记事本
   */

  isDefault?: boolean;
  /**
   * 更新时间
   */

  modifyTime?: string;
  /**
   * 记事本名称
   */

  name?: string;
  /**
   * 排序号
   */

  sortNo?: number;
}
export interface NotebookUpdateDTO {
  /**
   * 记事本名称
   */

  name: string;
  /**
   * 排序号
   */

  sortNo?: number;
}
export interface PurchaserResponseDTO {
  /**
   * 头像地址
   */

  avatar?: string;
  /**
   * 生日，格式：yyyy-MM-dd
   */

  birthday?: string;
  /**
   * 用户编码
   */

  code?: string;
  /**
   * 最近登录时间，格式：yyyy-MM-dd HH:mm:ss
   */

  lastLoginTime?: string;
  /**
   * 昵称
   */

  name?: string;
  /**
   * 手机号
   */

  phone?: string;
  /**
   * 性别
   */

  sex?: string;
  /**
   * 账号状态
   */

  state?: string;
}

declare global {
  interface Apis {
    contact: {
      /**
       * ---
       *
       * [GET] 查询联系人列表
       *
       * **path:** /contact
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应内容
       *   // [items] start
       *   // [title] ContactResponseDTO
       *   // 联系人响应DTO
       *   // [items] end
       *   data?: Array<{
       *     // 生日
       *     birthday?: string
       *     // 公司地址
       *     companyAddress?: string
       *     // 公司名称
       *     companyName?: string
       *     // 创建时间
       *     createTime?: string
       *     // 部门
       *     department?: string
       *     // 家庭地址
       *     homeAddress?: string
       *     // 联系人ID
       *     id?: number
       *     // 是否关注
       *     isFollow?: boolean
       *     // 更新时间
       *     modifyTime?: string
       *     // 联系人姓名
       *     name?: string
       *     // 记事本ID
       *     notebookId?: number
       *     // 联系电话列表
       *     // [items] start
       *     // [title] ContactPhoneDTO
       *     // 联系电话信息DTO
       *     // [items] end
       *     phones?: Array<{
       *       // 联系电话
       *       phone?: string
       *       // 电话类型
       *       type?: string
       *     }>
       *     // 职位
       *     position?: string
       *     // 性别
       *     sex?: string
       *     // 来源
       *     source?: string
       *   }>
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      getContacts<Config extends Alova2MethodConfig<_List_ContactResponseDTO_>>(
        config?: Config
      ): Alova2Method<_List_ContactResponseDTO_, 'contact.getContacts', Config>;
      /**
       * ---
       *
       * [POST] 创建联系人
       *
       * **path:** /contact
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 生日日期
       *   birthday?: string
       *   // 公司地址
       *   companyAddress?: string
       *   // 公司名称
       *   companyName?: string
       *   // 部门
       *   department?: string
       *   // 家庭地址
       *   homeAddress?: string
       *   // 是否关注
       *   isFollow?: boolean
       *   // 联系人姓名
       *   name: string
       *   // 记事本ID
       *   notebookId: number
       *   // 联系电话列表
       *   // [items] start
       *   // [title] ContactPhoneDTO
       *   // 联系电话信息DTO
       *   // [items] end
       *   phones?: Array<{
       *     // 联系电话
       *     phone?: string
       *     // 电话类型
       *     type?: string
       *   }>
       *   // 职位
       *   position?: string
       *   // 性别
       *   sex?: string
       *   // 来源
       *   source?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] ContactResponseDTO
       *   // 联系人响应DTO
       *   data?: {
       *     // 生日
       *     birthday?: string
       *     // 公司地址
       *     companyAddress?: string
       *     // 公司名称
       *     companyName?: string
       *     // 创建时间
       *     createTime?: string
       *     // 部门
       *     department?: string
       *     // 家庭地址
       *     homeAddress?: string
       *     // 联系人ID
       *     id?: number
       *     // 是否关注
       *     isFollow?: boolean
       *     // 更新时间
       *     modifyTime?: string
       *     // 联系人姓名
       *     name?: string
       *     // 记事本ID
       *     notebookId?: number
       *     // 联系电话列表
       *     // [items] start
       *     // [title] ContactPhoneDTO
       *     // 联系电话信息DTO
       *     // [items] end
       *     phones?: Array<{
       *       // 联系电话
       *       phone?: string
       *       // 电话类型
       *       type?: string
       *     }>
       *     // 职位
       *     position?: string
       *     // 性别
       *     sex?: string
       *     // 来源
       *     source?: string
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      createContact<
        Config extends Alova2MethodConfig<_ContactResponseDTO_> & {
          data: ContactDTO;
        }
      >(
        config: Config
      ): Alova2Method<_ContactResponseDTO_, 'contact.createContact', Config>;
      /**
       * ---
       *
       * [GET] 查询记事本联系人
       *
       * **path:** /contact/notebook/{notebookId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // notebookId
       *   notebookId: number
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // keyword
       *   keyword?: string
       *   // onlyFollow
       *   onlyFollow?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应内容
       *   // [items] start
       *   // [title] ContactResponseDTO
       *   // 联系人响应DTO
       *   // [items] end
       *   data?: Array<{
       *     // 生日
       *     birthday?: string
       *     // 公司地址
       *     companyAddress?: string
       *     // 公司名称
       *     companyName?: string
       *     // 创建时间
       *     createTime?: string
       *     // 部门
       *     department?: string
       *     // 家庭地址
       *     homeAddress?: string
       *     // 联系人ID
       *     id?: number
       *     // 是否关注
       *     isFollow?: boolean
       *     // 更新时间
       *     modifyTime?: string
       *     // 联系人姓名
       *     name?: string
       *     // 记事本ID
       *     notebookId?: number
       *     // 联系电话列表
       *     // [items] start
       *     // [title] ContactPhoneDTO
       *     // 联系电话信息DTO
       *     // [items] end
       *     phones?: Array<{
       *       // 联系电话
       *       phone?: string
       *       // 电话类型
       *       type?: string
       *     }>
       *     // 职位
       *     position?: string
       *     // 性别
       *     sex?: string
       *     // 来源
       *     source?: string
       *   }>
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      getContactsByNotebook<
        Config extends Alova2MethodConfig<_List_ContactResponseDTO_> & {
          pathParams: {
            /**
             * notebookId
             */

            notebookId: number;
          };
          params: {
            /**
             * keyword
             */

            keyword?: string;
            /**
             * onlyFollow
             */

            onlyFollow?: boolean;
          };
        }
      >(
        config: Config
      ): Alova2Method<_List_ContactResponseDTO_, 'contact.getContactsByNotebook', Config>;
      /**
       * ---
       *
       * [GET] 分页查询联系人和统计
       *
       * **path:** /contact/notebook/{notebookId}/page
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // notebookId
       *   notebookId: number
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // endTime
       *   endTime?: string
       *   // keyword
       *   keyword?: string
       *   // onlyFollow
       *   onlyFollow?: boolean
       *   // pageNo
       *   pageNo?: number
       *   // pageSize
       *   pageSize?: number
       *   // startTime
       *   startTime?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] ContactPageResponseDTO
       *   // 人脉分页查询响应数据
       *   data?: {
       *     // 当前页码，从1开始
       *     pageNo?: number
       *     // 每页数量
       *     pageSize?: number
       *     // 当前页数据
       *     // [items] start
       *     // [title] ContactResponseDTO
       *     // 联系人响应DTO
       *     // [items] end
       *     records?: Array<{
       *       // 生日
       *       birthday?: string
       *       // 公司地址
       *       companyAddress?: string
       *       // 公司名称
       *       companyName?: string
       *       // 创建时间
       *       createTime?: string
       *       // 部门
       *       department?: string
       *       // 家庭地址
       *       homeAddress?: string
       *       // 联系人ID
       *       id?: number
       *       // 是否关注
       *       isFollow?: boolean
       *       // 更新时间
       *       modifyTime?: string
       *       // 联系人姓名
       *       name?: string
       *       // 记事本ID
       *       notebookId?: number
       *       // 联系电话列表
       *       // [items] start
       *       // [title] ContactPhoneDTO
       *       // 联系电话信息DTO
       *       // [items] end
       *       phones?: Array<{
       *         // 联系电话
       *         phone?: string
       *         // 电话类型
       *         type?: string
       *       }>
       *       // 职位
       *       position?: string
       *       // 性别
       *       sex?: string
       *       // 来源
       *       source?: string
       *     }>
       *     // [title] ContactListStatsDTO
       *     // 人脉列表统计数据
       *     stats?: {
       *       // 产生成交的联系人数量
       *       dealContacts?: number
       *       // 产生支出的联系人数量
       *       expenseContacts?: number
       *       // 新增人脉数量
       *       newContacts?: number
       *     }
       *     // 总记录数
       *     total?: number
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      pageContacts<
        Config extends Alova2MethodConfig<_ContactPageResponseDTO_> & {
          pathParams: {
            /**
             * notebookId
             */

            notebookId: number;
          };
          params: {
            /**
             * endTime
             */

            endTime?: string;
            /**
             * keyword
             */

            keyword?: string;
            /**
             * onlyFollow
             */

            onlyFollow?: boolean;
            /**
             * pageNo
             */

            pageNo?: number;
            /**
             * pageSize
             */

            pageSize?: number;
            /**
             * startTime
             */

            startTime?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<_ContactPageResponseDTO_, 'contact.pageContacts', Config>;
      /**
       * ---
       *
       * [GET] 查询联系人详情
       *
       * **path:** /contact/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // id
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] ContactResponseDTO
       *   // 联系人响应DTO
       *   data?: {
       *     // 生日
       *     birthday?: string
       *     // 公司地址
       *     companyAddress?: string
       *     // 公司名称
       *     companyName?: string
       *     // 创建时间
       *     createTime?: string
       *     // 部门
       *     department?: string
       *     // 家庭地址
       *     homeAddress?: string
       *     // 联系人ID
       *     id?: number
       *     // 是否关注
       *     isFollow?: boolean
       *     // 更新时间
       *     modifyTime?: string
       *     // 联系人姓名
       *     name?: string
       *     // 记事本ID
       *     notebookId?: number
       *     // 联系电话列表
       *     // [items] start
       *     // [title] ContactPhoneDTO
       *     // 联系电话信息DTO
       *     // [items] end
       *     phones?: Array<{
       *       // 联系电话
       *       phone?: string
       *       // 电话类型
       *       type?: string
       *     }>
       *     // 职位
       *     position?: string
       *     // 性别
       *     sex?: string
       *     // 来源
       *     source?: string
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      getContact<
        Config extends Alova2MethodConfig<_ContactResponseDTO_> & {
          pathParams: {
            /**
             * id
             */

            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<_ContactResponseDTO_, 'contact.getContact', Config>;
      /**
       * ---
       *
       * [PUT] 更新联系人
       *
       * **path:** /contact/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // id
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 生日日期
       *   birthday?: string
       *   // 公司地址
       *   companyAddress?: string
       *   // 公司名称
       *   companyName?: string
       *   // 部门
       *   department?: string
       *   // 家庭地址
       *   homeAddress?: string
       *   // 是否关注
       *   isFollow?: boolean
       *   // 联系人姓名
       *   name: string
       *   // 记事本ID
       *   notebookId: number
       *   // 联系电话列表
       *   // [items] start
       *   // [title] ContactPhoneDTO
       *   // 联系电话信息DTO
       *   // [items] end
       *   phones?: Array<{
       *     // 联系电话
       *     phone?: string
       *     // 电话类型
       *     type?: string
       *   }>
       *   // 职位
       *   position?: string
       *   // 性别
       *   sex?: string
       *   // 来源
       *   source?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] ContactResponseDTO
       *   // 联系人响应DTO
       *   data?: {
       *     // 生日
       *     birthday?: string
       *     // 公司地址
       *     companyAddress?: string
       *     // 公司名称
       *     companyName?: string
       *     // 创建时间
       *     createTime?: string
       *     // 部门
       *     department?: string
       *     // 家庭地址
       *     homeAddress?: string
       *     // 联系人ID
       *     id?: number
       *     // 是否关注
       *     isFollow?: boolean
       *     // 更新时间
       *     modifyTime?: string
       *     // 联系人姓名
       *     name?: string
       *     // 记事本ID
       *     notebookId?: number
       *     // 联系电话列表
       *     // [items] start
       *     // [title] ContactPhoneDTO
       *     // 联系电话信息DTO
       *     // [items] end
       *     phones?: Array<{
       *       // 联系电话
       *       phone?: string
       *       // 电话类型
       *       type?: string
       *     }>
       *     // 职位
       *     position?: string
       *     // 性别
       *     sex?: string
       *     // 来源
       *     source?: string
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      updateContact<
        Config extends Alova2MethodConfig<_ContactResponseDTO_> & {
          pathParams: {
            /**
             * id
             */

            id: number;
          };
          data: ContactDTO;
        }
      >(
        config: Config
      ): Alova2Method<_ContactResponseDTO_, 'contact.updateContact', Config>;
      /**
       * ---
       *
       * [DELETE] 删除联系人
       *
       * **path:** /contact/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // id
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      deleteContact<
        Config extends Alova2MethodConfig<_Void_> & {
          pathParams: {
            /**
             * id
             */

            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<_Void_, 'contact.deleteContact', Config>;
      /**
       * ---
       *
       * [PUT] 设置关注状态
       *
       * **path:** /contact/{id}/follow
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // id
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // isFollow
       *   isFollow: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      setFollowStatus<
        Config extends Alova2MethodConfig<_Void_> & {
          pathParams: {
            /**
             * id
             */

            id: number;
          };
          params: {
            /**
             * isFollow
             */

            isFollow: boolean;
          };
        }
      >(
        config: Config
      ): Alova2Method<_Void_, 'contact.setFollowStatus', Config>;
      /**
       * ---
       *
       * [GET] 查询联系人详情聚合数据
       *
       * **path:** /contact/{id}/overview
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // id
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] ContactOverviewResponseDTO
       *   // 联系人详情聚合响应数据
       *   data?: {
       *     // [title] ContactResponseDTO
       *     // 联系人响应DTO
       *     contact?: {
       *       // 生日
       *       birthday?: string
       *       // 公司地址
       *       companyAddress?: string
       *       // 公司名称
       *       companyName?: string
       *       // 创建时间
       *       createTime?: string
       *       // 部门
       *       department?: string
       *       // 家庭地址
       *       homeAddress?: string
       *       // 联系人ID
       *       id?: number
       *       // 是否关注
       *       isFollow?: boolean
       *       // 更新时间
       *       modifyTime?: string
       *       // 联系人姓名
       *       name?: string
       *       // 记事本ID
       *       notebookId?: number
       *       // 联系电话列表
       *       // [items] start
       *       // [title] ContactPhoneDTO
       *       // 联系电话信息DTO
       *       // [items] end
       *       phones?: Array<{
       *         // 联系电话
       *         phone?: string
       *         // 电话类型
       *         type?: string
       *       }>
       *       // 职位
       *       position?: string
       *       // 性别
       *       sex?: string
       *       // 来源
       *       source?: string
       *     }
       *     // 联系人收支记录
       *     // [items] start
       *     // [title] FinanceRecordResponseDTO
       *     // 收支记录响应数据
       *     // [items] end
       *     financeRecords?: Array<{
       *       // 金额
       *       amount?: number
       *       // 收支分类：成交、支出
       *       category?: string
       *       // 联系人ID
       *       contactId?: number
       *       // 创建时间，格式：yyyy-MM-dd HH:mm:ss
       *       createTime?: string
       *       // 发生时间，格式：yyyy-MM-dd HH:mm:ss
       *       eventTime?: string
       *       // 收支记录ID
       *       id?: number
       *       // 是否退款
       *       isRefund?: boolean
       *       // 更新时间，格式：yyyy-MM-dd HH:mm:ss
       *       modifyTime?: string
       *       // 记事本ID
       *       notebookId?: number
       *       // 备注
       *       remark?: string
       *       // 收支类型ID
       *       typeId?: number
       *       // 收支类型名称
       *       typeName?: string
       *     }>
       *     // [title] ContactFinanceStatsDTO
       *     // 联系人收支统计数据
       *     financeStats?: {
       *       // 差额，成交总额减支出总额
       *       balance?: number
       *       // 成交总额，不含退款
       *       dealAmount?: number
       *       // 成交记录数量，不含退款
       *       dealCount?: number
       *       // 支出总额，不含退款
       *       expenseAmount?: number
       *       // 支出记录数量，不含退款
       *       expenseCount?: number
       *     }
       *     // 最近十条跟进记事
       *     // [items] start
       *     // [title] ContactNoteResponseDTO
       *     // 跟进记事响应数据
       *     // [items] end
       *     recentNotes?: Array<{
       *       // 通话时长，单位：秒
       *       callDuration?: number
       *       // 通话类型
       *       callType?: string
       *       // 联系人ID
       *       contactId?: number
       *       // 记事内容
       *       content?: string
       *       // 创建时间，格式：yyyy-MM-dd HH:mm:ss
       *       createTime?: string
       *       // 事件发生时间，格式：yyyy-MM-dd HH:mm:ss
       *       eventTime?: string
       *       // 跟进记事ID
       *       id?: number
       *       // 拜访纬度
       *       lat?: number
       *       // 拜访经度
       *       lng?: number
       *       // 更新时间，格式：yyyy-MM-dd HH:mm:ss
       *       modifyTime?: string
       *       // 记事类型：call-电话联系，sms-短信联系，normal-普通记事，visit-拜访记事
       *       noteType?: string
       *       // 记事本ID
       *       notebookId?: number
       *       // 联系电话
       *       phone?: string
       *       // 短信类型
       *       smsType?: string
       *       // 拜访地址
       *       visitAddress?: string
       *     }>
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      getContactOverview<
        Config extends Alova2MethodConfig<_ContactOverviewResponseDTO_> & {
          pathParams: {
            /**
             * id
             */

            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<_ContactOverviewResponseDTO_, 'contact.getContactOverview', Config>;
    };
    contactNote: {
      /**
       * ---
       *
       * [POST] 创建跟进记事
       *
       * **path:** /contact-note
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 通话时长，单位：秒
       *   callDuration?: number
       *   // 通话类型：in-呼入，out-呼出
       *   callType?: string
       *   // 联系人ID
       *   contactId: number
       *   // 记事内容
       *   content?: string
       *   // 事件发生时间，格式：yyyy-MM-dd HH:mm:ss
       *   eventTime?: string
       *   // 拜访纬度
       *   lat?: number
       *   // 拜访经度
       *   lng?: number
       *   // 记事类型：call-电话联系，sms-短信联系，normal-普通记事，visit-拜访记事
       *   noteType: string
       *   // 记事本ID
       *   notebookId: number
       *   // 联系电话
       *   phone?: string
       *   // 短信类型：in-接收，out-发送
       *   smsType?: string
       *   // 拜访地址
       *   visitAddress?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] ContactNoteResponseDTO
       *   // 跟进记事响应数据
       *   data?: {
       *     // 通话时长，单位：秒
       *     callDuration?: number
       *     // 通话类型
       *     callType?: string
       *     // 联系人ID
       *     contactId?: number
       *     // 记事内容
       *     content?: string
       *     // 创建时间，格式：yyyy-MM-dd HH:mm:ss
       *     createTime?: string
       *     // 事件发生时间，格式：yyyy-MM-dd HH:mm:ss
       *     eventTime?: string
       *     // 跟进记事ID
       *     id?: number
       *     // 拜访纬度
       *     lat?: number
       *     // 拜访经度
       *     lng?: number
       *     // 更新时间，格式：yyyy-MM-dd HH:mm:ss
       *     modifyTime?: string
       *     // 记事类型：call-电话联系，sms-短信联系，normal-普通记事，visit-拜访记事
       *     noteType?: string
       *     // 记事本ID
       *     notebookId?: number
       *     // 联系电话
       *     phone?: string
       *     // 短信类型
       *     smsType?: string
       *     // 拜访地址
       *     visitAddress?: string
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<_ContactNoteResponseDTO_> & {
          data: ContactNoteDTO;
        }
      >(
        config: Config
      ): Alova2Method<_ContactNoteResponseDTO_, 'contactNote.create', Config>;
      /**
       * ---
       *
       * [GET] 查询跟进记事
       *
       * **path:** /contact-note/contact/{contactId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // contactId
       *   contactId: number
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // limit
       *   limit?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应内容
       *   // [items] start
       *   // [title] ContactNoteResponseDTO
       *   // 跟进记事响应数据
       *   // [items] end
       *   data?: Array<{
       *     // 通话时长，单位：秒
       *     callDuration?: number
       *     // 通话类型
       *     callType?: string
       *     // 联系人ID
       *     contactId?: number
       *     // 记事内容
       *     content?: string
       *     // 创建时间，格式：yyyy-MM-dd HH:mm:ss
       *     createTime?: string
       *     // 事件发生时间，格式：yyyy-MM-dd HH:mm:ss
       *     eventTime?: string
       *     // 跟进记事ID
       *     id?: number
       *     // 拜访纬度
       *     lat?: number
       *     // 拜访经度
       *     lng?: number
       *     // 更新时间，格式：yyyy-MM-dd HH:mm:ss
       *     modifyTime?: string
       *     // 记事类型：call-电话联系，sms-短信联系，normal-普通记事，visit-拜访记事
       *     noteType?: string
       *     // 记事本ID
       *     notebookId?: number
       *     // 联系电话
       *     phone?: string
       *     // 短信类型
       *     smsType?: string
       *     // 拜访地址
       *     visitAddress?: string
       *   }>
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      list<
        Config extends Alova2MethodConfig<_List_ContactNoteResponseDTO_> & {
          pathParams: {
            /**
             * contactId
             */

            contactId: number;
          };
          params: {
            /**
             * limit
             */

            limit?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<_List_ContactNoteResponseDTO_, 'contactNote.list', Config>;
    };
    district: {
      /**
       * ---
       *
       * [GET] 区域列表-下拉搜索
       *
       * **path:** /district/list
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应内容
       *   // [items] start
       *   // [title] DistrictLevelDto
       *   // [items] end
       *   data?: Array<{
       *     // 行政区划代码
       *     code?: string
       *     // 行政区
       *     district?: string
       *     id?: number
       *     // 级别
       *     level?: number
       *     // 下级行政区列表
       *     // [items] start
       *     // [cycle] $.data.[]
       *     // [items] end
       *     list?: DistrictLevelDto[]
       *     // 父级id
       *     parentId?: number
       *   }>
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      list<Config extends Alova2MethodConfig<_List_DistrictLevelDto_>>(
        config?: Config
      ): Alova2Method<_List_DistrictLevelDto_, 'district.list', Config>;
      /**
       * ---
       *
       * [GET] 区域树
       *
       * **path:** /district/tree
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 是否包含城市,true 包含 false 不包含
       *   isIncludeCity?: boolean
       *   // 模糊查询
       *   likeName?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应内容
       *   // [items] start
       *   // [title] 区域树实体
       *   // [items] end
       *   data?: Array<{
       *     // 区域树
       *     // [items] start
       *     // [cycle] $.data.[]
       *     // [items] end
       *     children?: _[]
       *     // 区域代码
       *     districtCode?: string
       *     // 区域ID
       *     districtId?: number
       *     // 区域名称
       *     districtName?: string
       *     // 区域父级
       *     districtParentId?: number
       *   }>
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      getDistrictTree<
        Config extends Alova2MethodConfig<_List_> & {
          params: {
            /**
             * 是否包含城市,true 包含 false 不包含
             */

            isIncludeCity?: boolean;
            /**
             * 模糊查询
             */

            likeName?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<_List_, 'district.getDistrictTree', Config>;
    };
    file: {
      /**
       * ---
       *
       * [GET] 生成Token
       *
       * **path:** /file/token
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 类型（SIMPLE;OVERWRITE）
       *   type: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] 生成token
       *   data?: {
       *     // 上传Token
       *     token?: string
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      uploadToken<
        Config extends Alova2MethodConfig<_token_> & {
          params: {
            /**
             * 类型（SIMPLE;OVERWRITE）
             */

            type: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<_token_, 'file.uploadToken', Config>;
      /**
       * ---
       *
       * [POST] 文件上传
       *
       * **path:** /file/upload
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // 文件类型(头像：PORTRAIT; 门店LOGO：STORE_LOGO_IMG, 门店安全图片：STORE_SAFE_IMG, 门店资质图片：STORE_CERTIFICATION_IMG, 组织分区图片：ORG_LOGO_IMG, 失物招领：LOSTFIND, 执照：LICENSE, 商品图：PRODUCT, 核酸检测附件：NUCLEATE),捎带员签到上传图：DELIVERY,发起问卷投票活动图片：QUESTIONNAIRE订单评论图片：COMMENT_IMG, 身份证：ID_CARD_IMG, 健康证：HEALTH_CARDS, 厨师订单售后：COOK_AFTER_SALE
       *   type?: string
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // file
       *   file?: Blob
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应内容
       *   data?: Record<string, object>
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      uploadFile<
        Config extends Alova2MethodConfig<_HashMap_> & {
          params: {
            /**
             * 文件类型(头像：PORTRAIT; 门店LOGO：STORE_LOGO_IMG, 门店安全图片：STORE_SAFE_IMG, 门店资质图片：STORE_CERTIFICATION_IMG, 组织分区图片：ORG_LOGO_IMG, 失物招领：LOSTFIND, 执照：LICENSE, 商品图：PRODUCT, 核酸检测附件：NUCLEATE),捎带员签到上传图：DELIVERY,发起问卷投票活动图片：QUESTIONNAIRE订单评论图片：COMMENT_IMG, 身份证：ID_CARD_IMG, 健康证：HEALTH_CARDS, 厨师订单售后：COOK_AFTER_SALE
             */

            type?: string;
          };
          data: {
            /**
             * file
             */

            file?: Blob;
          };
        }
      >(
        config: Config
      ): Alova2Method<_HashMap_, 'file.uploadFile', Config>;
    };
    financeRecord: {
      /**
       * ---
       *
       * [POST] 创建收支记录
       *
       * **path:** /finance-record
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 金额，必须大于0
       *   amount: number
       *   // 收支分类：成交、支出
       *   category: string
       *   // 联系人ID，可为空
       *   contactId?: number
       *   // 发生时间，格式：yyyy-MM-dd HH:mm:ss
       *   eventTime?: string
       *   // 是否退款，退款记录不计入统计
       *   isRefund?: boolean
       *   // 记事本ID
       *   notebookId: number
       *   // 备注
       *   remark?: string
       *   // 收支类型ID
       *   typeId?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] FinanceRecordResponseDTO
       *   // 收支记录响应数据
       *   data?: {
       *     // 金额
       *     amount?: number
       *     // 收支分类：成交、支出
       *     category?: string
       *     // 联系人ID
       *     contactId?: number
       *     // 创建时间，格式：yyyy-MM-dd HH:mm:ss
       *     createTime?: string
       *     // 发生时间，格式：yyyy-MM-dd HH:mm:ss
       *     eventTime?: string
       *     // 收支记录ID
       *     id?: number
       *     // 是否退款
       *     isRefund?: boolean
       *     // 更新时间，格式：yyyy-MM-dd HH:mm:ss
       *     modifyTime?: string
       *     // 记事本ID
       *     notebookId?: number
       *     // 备注
       *     remark?: string
       *     // 收支类型ID
       *     typeId?: number
       *     // 收支类型名称
       *     typeName?: string
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<_FinanceRecordResponseDTO_> & {
          data: FinanceRecordDTO;
        }
      >(
        config: Config
      ): Alova2Method<_FinanceRecordResponseDTO_, 'financeRecord.create', Config>;
      /**
       * ---
       *
       * [GET] 查询收支记录
       *
       * **path:** /finance-record/notebook/{notebookId}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // notebookId
       *   notebookId: number
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // category
       *   category?: string
       *   // contactId
       *   contactId?: number
       *   // endTime
       *   endTime?: string
       *   // startTime
       *   startTime?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应内容
       *   // [items] start
       *   // [title] FinanceRecordResponseDTO
       *   // 收支记录响应数据
       *   // [items] end
       *   data?: Array<{
       *     // 金额
       *     amount?: number
       *     // 收支分类：成交、支出
       *     category?: string
       *     // 联系人ID
       *     contactId?: number
       *     // 创建时间，格式：yyyy-MM-dd HH:mm:ss
       *     createTime?: string
       *     // 发生时间，格式：yyyy-MM-dd HH:mm:ss
       *     eventTime?: string
       *     // 收支记录ID
       *     id?: number
       *     // 是否退款
       *     isRefund?: boolean
       *     // 更新时间，格式：yyyy-MM-dd HH:mm:ss
       *     modifyTime?: string
       *     // 记事本ID
       *     notebookId?: number
       *     // 备注
       *     remark?: string
       *     // 收支类型ID
       *     typeId?: number
       *     // 收支类型名称
       *     typeName?: string
       *   }>
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      list<
        Config extends Alova2MethodConfig<_List_FinanceRecordResponseDTO_> & {
          pathParams: {
            /**
             * notebookId
             */

            notebookId: number;
          };
          params: {
            /**
             * category
             */

            category?: string;
            /**
             * contactId
             */

            contactId?: number;
            /**
             * endTime
             */

            endTime?: string;
            /**
             * startTime
             */

            startTime?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<_List_FinanceRecordResponseDTO_, 'financeRecord.list', Config>;
      /**
       * ---
       *
       * [GET] 分页查询收支记录
       *
       * **path:** /finance-record/notebook/{notebookId}/page
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // notebookId
       *   notebookId: number
       * }
       * ```
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // category
       *   category?: string
       *   // contactId
       *   contactId?: number
       *   // endTime
       *   endTime?: string
       *   // pageNo
       *   pageNo?: number
       *   // pageSize
       *   pageSize?: number
       *   // startTime
       *   startTime?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] FinanceRecordPageResponseDTO
       *   // 收支记录分页响应数据
       *   data?: {
       *     // 当前页码，从1开始
       *     pageNo?: number
       *     // 每页数量
       *     pageSize?: number
       *     // 当前页数据
       *     // [items] start
       *     // [title] FinanceRecordResponseDTO
       *     // 收支记录响应数据
       *     // [items] end
       *     records?: Array<{
       *       // 金额
       *       amount?: number
       *       // 收支分类：成交、支出
       *       category?: string
       *       // 联系人ID
       *       contactId?: number
       *       // 创建时间，格式：yyyy-MM-dd HH:mm:ss
       *       createTime?: string
       *       // 发生时间，格式：yyyy-MM-dd HH:mm:ss
       *       eventTime?: string
       *       // 收支记录ID
       *       id?: number
       *       // 是否退款
       *       isRefund?: boolean
       *       // 更新时间，格式：yyyy-MM-dd HH:mm:ss
       *       modifyTime?: string
       *       // 记事本ID
       *       notebookId?: number
       *       // 备注
       *       remark?: string
       *       // 收支类型ID
       *       typeId?: number
       *       // 收支类型名称
       *       typeName?: string
       *     }>
       *     // 总记录数
       *     total?: number
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      page<
        Config extends Alova2MethodConfig<_FinanceRecordPageResponseDTO_> & {
          pathParams: {
            /**
             * notebookId
             */

            notebookId: number;
          };
          params: {
            /**
             * category
             */

            category?: string;
            /**
             * contactId
             */

            contactId?: number;
            /**
             * endTime
             */

            endTime?: string;
            /**
             * pageNo
             */

            pageNo?: number;
            /**
             * pageSize
             */

            pageSize?: number;
            /**
             * startTime
             */

            startTime?: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<_FinanceRecordPageResponseDTO_, 'financeRecord.page', Config>;
      /**
       * ---
       *
       * [GET] 查询收支记录详情
       *
       * **path:** /finance-record/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // id
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] FinanceRecordResponseDTO
       *   // 收支记录响应数据
       *   data?: {
       *     // 金额
       *     amount?: number
       *     // 收支分类：成交、支出
       *     category?: string
       *     // 联系人ID
       *     contactId?: number
       *     // 创建时间，格式：yyyy-MM-dd HH:mm:ss
       *     createTime?: string
       *     // 发生时间，格式：yyyy-MM-dd HH:mm:ss
       *     eventTime?: string
       *     // 收支记录ID
       *     id?: number
       *     // 是否退款
       *     isRefund?: boolean
       *     // 更新时间，格式：yyyy-MM-dd HH:mm:ss
       *     modifyTime?: string
       *     // 记事本ID
       *     notebookId?: number
       *     // 备注
       *     remark?: string
       *     // 收支类型ID
       *     typeId?: number
       *     // 收支类型名称
       *     typeName?: string
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      getDetail<
        Config extends Alova2MethodConfig<_FinanceRecordResponseDTO_> & {
          pathParams: {
            /**
             * id
             */

            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<_FinanceRecordResponseDTO_, 'financeRecord.getDetail', Config>;
      /**
       * ---
       *
       * [PUT] 更新收支记录
       *
       * **path:** /finance-record/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // id
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 金额，必须大于0
       *   amount: number
       *   // 收支分类：成交、支出
       *   category: string
       *   // 联系人ID，可为空
       *   contactId?: number
       *   // 发生时间，格式：yyyy-MM-dd HH:mm:ss
       *   eventTime?: string
       *   // 是否退款，退款记录不计入统计
       *   isRefund?: boolean
       *   // 记事本ID
       *   notebookId: number
       *   // 备注
       *   remark?: string
       *   // 收支类型ID
       *   typeId?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] FinanceRecordResponseDTO
       *   // 收支记录响应数据
       *   data?: {
       *     // 金额
       *     amount?: number
       *     // 收支分类：成交、支出
       *     category?: string
       *     // 联系人ID
       *     contactId?: number
       *     // 创建时间，格式：yyyy-MM-dd HH:mm:ss
       *     createTime?: string
       *     // 发生时间，格式：yyyy-MM-dd HH:mm:ss
       *     eventTime?: string
       *     // 收支记录ID
       *     id?: number
       *     // 是否退款
       *     isRefund?: boolean
       *     // 更新时间，格式：yyyy-MM-dd HH:mm:ss
       *     modifyTime?: string
       *     // 记事本ID
       *     notebookId?: number
       *     // 备注
       *     remark?: string
       *     // 收支类型ID
       *     typeId?: number
       *     // 收支类型名称
       *     typeName?: string
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      update<
        Config extends Alova2MethodConfig<_FinanceRecordResponseDTO_> & {
          pathParams: {
            /**
             * id
             */

            id: number;
          };
          data: FinanceRecordDTO;
        }
      >(
        config: Config
      ): Alova2Method<_FinanceRecordResponseDTO_, 'financeRecord.update', Config>;
      /**
       * ---
       *
       * [DELETE] 删除收支记录
       *
       * **path:** /finance-record/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // id
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      delete<
        Config extends Alova2MethodConfig<_Void_> & {
          pathParams: {
            /**
             * id
             */

            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<_Void_, 'financeRecord.delete', Config>;
    };
    financeType: {
      /**
       * ---
       *
       * [GET] 查询收支类型
       *
       * **path:** /finance-type
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应内容
       *   // [items] start
       *   // [title] FinanceTypeResponseDTO
       *   // 收支类型响应数据
       *   // [items] end
       *   data?: Array<{
       *     // 创建时间，格式：yyyy-MM-dd HH:mm:ss
       *     createTime?: string
       *     // 类型ID
       *     id?: number
       *     // 更新时间，格式：yyyy-MM-dd HH:mm:ss
       *     modifyTime?: string
       *     // 排序号
       *     sortNo?: number
       *     // 类型分类：成交、支出
       *     typeCategory?: string
       *     // 类型名称
       *     typeName?: string
       *   }>
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      list<Config extends Alova2MethodConfig<_List_FinanceTypeResponseDTO_>>(
        config?: Config
      ): Alova2Method<_List_FinanceTypeResponseDTO_, 'financeType.list', Config>;
      /**
       * ---
       *
       * [POST] 创建收支类型
       *
       * **path:** /finance-type
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 排序号
       *   sortNo?: number
       *   // 类型分类：成交、支出
       *   typeCategory: string
       *   // 类型名称
       *   typeName: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] FinanceTypeResponseDTO
       *   // 收支类型响应数据
       *   data?: {
       *     // 创建时间，格式：yyyy-MM-dd HH:mm:ss
       *     createTime?: string
       *     // 类型ID
       *     id?: number
       *     // 更新时间，格式：yyyy-MM-dd HH:mm:ss
       *     modifyTime?: string
       *     // 排序号
       *     sortNo?: number
       *     // 类型分类：成交、支出
       *     typeCategory?: string
       *     // 类型名称
       *     typeName?: string
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<_FinanceTypeResponseDTO_> & {
          data: FinanceTypeDTO;
        }
      >(
        config: Config
      ): Alova2Method<_FinanceTypeResponseDTO_, 'financeType.create', Config>;
      /**
       * ---
       *
       * [PUT] 修改收支类型
       *
       * **path:** /finance-type/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // id
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 排序号
       *   sortNo?: number
       *   // 类型分类：成交、支出
       *   typeCategory: string
       *   // 类型名称
       *   typeName: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] FinanceTypeResponseDTO
       *   // 收支类型响应数据
       *   data?: {
       *     // 创建时间，格式：yyyy-MM-dd HH:mm:ss
       *     createTime?: string
       *     // 类型ID
       *     id?: number
       *     // 更新时间，格式：yyyy-MM-dd HH:mm:ss
       *     modifyTime?: string
       *     // 排序号
       *     sortNo?: number
       *     // 类型分类：成交、支出
       *     typeCategory?: string
       *     // 类型名称
       *     typeName?: string
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      update<
        Config extends Alova2MethodConfig<_FinanceTypeResponseDTO_> & {
          pathParams: {
            /**
             * id
             */

            id: number;
          };
          data: FinanceTypeDTO;
        }
      >(
        config: Config
      ): Alova2Method<_FinanceTypeResponseDTO_, 'financeType.update', Config>;
      /**
       * ---
       *
       * [DELETE] 删除收支类型
       *
       * **path:** /finance-type/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // id
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      delete<
        Config extends Alova2MethodConfig<_Void_> & {
          pathParams: {
            /**
             * id
             */

            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<_Void_, 'financeType.delete', Config>;
    };
    gate: {
      /**
       * ---
       *
       * [POST] 电话登录
       *
       * **path:** /gate/login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 验证码
       *   code?: string
       *   // 密码
       *   password?: string
       *   // 电话号码
       *   phone: string
       *   // 登录类型:1验证码2密码
       *   type: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应内容
       *   data?: string
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      login<
        Config extends Alova2MethodConfig<_string_> & {
          data: _5;
        }
      >(
        config: Config
      ): Alova2Method<_string_, 'gate.login', Config>;
      /**
       * ---
       *
       * [POST] 获取短信验证码
       *
       * **path:** /gate/phoneVerification
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 电话号码
       *   phone: string
       *   // 密钥 secret规则: 6位随机数 + MD5(phone+type+ORIGIN_SECRET) + millis（13位） + 6位随机数
       *   secret: string
       *   // 验证码类型 登录：0
       *   type: string
       *   valid?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应内容
       *   data?: object
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      phoneVerificationCode<
        Config extends Alova2MethodConfig<_3> & {
          data: _2;
        }
      >(
        config: Config
      ): Alova2Method<_3, 'gate.phoneVerificationCode', Config>;
    };
    notebook: {
      /**
       * ---
       *
       * [GET] 获取用户所有记事本
       *
       * **path:** /notebook
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应内容
       *   // [items] start
       *   // [title] NotebookResponseDTO
       *   // 记事本响应数据
       *   // [items] end
       *   data?: Array<{
       *     // 创建时间
       *     createTime?: string
       *     // 记事本ID
       *     id?: number
       *     // 是否默认记事本
       *     isDefault?: boolean
       *     // 更新时间
       *     modifyTime?: string
       *     // 记事本名称
       *     name?: string
       *     // 排序号
       *     sortNo?: number
       *   }>
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      getNotebooks<Config extends Alova2MethodConfig<_List_NotebookResponseDTO_>>(
        config?: Config
      ): Alova2Method<_List_NotebookResponseDTO_, 'notebook.getNotebooks', Config>;
      /**
       * ---
       *
       * [POST] 创建新记事本
       *
       * **path:** /notebook
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 记事本名称
       *   name: string
       *   // 排序号
       *   sortNo?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] NotebookResponseDTO
       *   // 记事本响应数据
       *   data?: {
       *     // 创建时间
       *     createTime?: string
       *     // 记事本ID
       *     id?: number
       *     // 是否默认记事本
       *     isDefault?: boolean
       *     // 更新时间
       *     modifyTime?: string
       *     // 记事本名称
       *     name?: string
       *     // 排序号
       *     sortNo?: number
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      createNotebook<
        Config extends Alova2MethodConfig<_NotebookResponseDTO_> & {
          data: NotebookDTO;
        }
      >(
        config: Config
      ): Alova2Method<_NotebookResponseDTO_, 'notebook.createNotebook', Config>;
      /**
       * ---
       *
       * [PUT] 更新记事本信息
       *
       * **path:** /notebook/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // id
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 记事本名称
       *   name: string
       *   // 排序号
       *   sortNo?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] NotebookResponseDTO
       *   // 记事本响应数据
       *   data?: {
       *     // 创建时间
       *     createTime?: string
       *     // 记事本ID
       *     id?: number
       *     // 是否默认记事本
       *     isDefault?: boolean
       *     // 更新时间
       *     modifyTime?: string
       *     // 记事本名称
       *     name?: string
       *     // 排序号
       *     sortNo?: number
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      updateNotebook<
        Config extends Alova2MethodConfig<_NotebookResponseDTO_> & {
          pathParams: {
            /**
             * id
             */

            id: number;
          };
          data: NotebookUpdateDTO;
        }
      >(
        config: Config
      ): Alova2Method<_NotebookResponseDTO_, 'notebook.updateNotebook', Config>;
      /**
       * ---
       *
       * [DELETE] 删除记事本
       *
       * **path:** /notebook/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // id
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应内容
       *   data?: object
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      deleteNotebook<
        Config extends Alova2MethodConfig<_3> & {
          pathParams: {
            /**
             * id
             */

            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<_3, 'notebook.deleteNotebook', Config>;
      /**
       * ---
       *
       * [PUT] 设置默认记事本
       *
       * **path:** /notebook/{id}/default
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   // id
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应内容
       *   data?: object
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      setDefaultNotebook<
        Config extends Alova2MethodConfig<_3> & {
          pathParams: {
            /**
             * id
             */

            id: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<_3, 'notebook.setDefaultNotebook', Config>;
    };
    purchaser: {
      /**
       * ---
       *
       * [GET] 设置头像
       *
       * **path:** /purchaser/avatar
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // avatarUrl
       *   avatarUrl: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] PurchaserResponseDTO
       *   // 当前用户响应数据
       *   data?: {
       *     // 头像地址
       *     avatar?: string
       *     // 生日，格式：yyyy-MM-dd
       *     birthday?: string
       *     // 用户编码
       *     code?: string
       *     // 最近登录时间，格式：yyyy-MM-dd HH:mm:ss
       *     lastLoginTime?: string
       *     // 昵称
       *     name?: string
       *     // 手机号
       *     phone?: string
       *     // 性别
       *     sex?: string
       *     // 账号状态
       *     state?: string
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      setAvatar<
        Config extends Alova2MethodConfig<_PurchaserResponseDTO_> & {
          params: {
            /**
             * avatarUrl
             */

            avatarUrl: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<_PurchaserResponseDTO_, 'purchaser.setAvatar', Config>;
      /**
       * ---
       *
       * [POST] 设置生日
       *
       * **path:** /purchaser/birthday
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 生日
       *   birthday: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] PurchaserResponseDTO
       *   // 当前用户响应数据
       *   data?: {
       *     // 头像地址
       *     avatar?: string
       *     // 生日，格式：yyyy-MM-dd
       *     birthday?: string
       *     // 用户编码
       *     code?: string
       *     // 最近登录时间，格式：yyyy-MM-dd HH:mm:ss
       *     lastLoginTime?: string
       *     // 昵称
       *     name?: string
       *     // 手机号
       *     phone?: string
       *     // 性别
       *     sex?: string
       *     // 账号状态
       *     state?: string
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      setBirthday<
        Config extends Alova2MethodConfig<_PurchaserResponseDTO_> & {
          data: _DTO2;
        }
      >(
        config: Config
      ): Alova2Method<_PurchaserResponseDTO_, 'purchaser.setBirthday', Config>;
      /**
       * ---
       *
       * [POST] 设置昵称
       *
       * **path:** /purchaser/nickname
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = string
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] PurchaserResponseDTO
       *   // 当前用户响应数据
       *   data?: {
       *     // 头像地址
       *     avatar?: string
       *     // 生日，格式：yyyy-MM-dd
       *     birthday?: string
       *     // 用户编码
       *     code?: string
       *     // 最近登录时间，格式：yyyy-MM-dd HH:mm:ss
       *     lastLoginTime?: string
       *     // 昵称
       *     name?: string
       *     // 手机号
       *     phone?: string
       *     // 性别
       *     sex?: string
       *     // 账号状态
       *     state?: string
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      setNickname<
        Config extends Alova2MethodConfig<_PurchaserResponseDTO_> & {
          data: string;
        }
      >(
        config: Config
      ): Alova2Method<_PurchaserResponseDTO_, 'purchaser.setNickname', Config>;
      /**
       * ---
       *
       * [POST] 设置密码
       *
       * **path:** /purchaser/set/password
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 新密码
       *   newPassword: string
       *   // 原密码
       *   oldPassword: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] PurchaserResponseDTO
       *   // 当前用户响应数据
       *   data?: {
       *     // 头像地址
       *     avatar?: string
       *     // 生日，格式：yyyy-MM-dd
       *     birthday?: string
       *     // 用户编码
       *     code?: string
       *     // 最近登录时间，格式：yyyy-MM-dd HH:mm:ss
       *     lastLoginTime?: string
       *     // 昵称
       *     name?: string
       *     // 手机号
       *     phone?: string
       *     // 性别
       *     sex?: string
       *     // 账号状态
       *     state?: string
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      setPassword<
        Config extends Alova2MethodConfig<_PurchaserResponseDTO_> & {
          data: _DTO;
        }
      >(
        config: Config
      ): Alova2Method<_PurchaserResponseDTO_, 'purchaser.setPassword', Config>;
      /**
       * ---
       *
       * [GET] 设置性别
       *
       * **path:** /purchaser/sex
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // sex
       *   sex: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] PurchaserResponseDTO
       *   // 当前用户响应数据
       *   data?: {
       *     // 头像地址
       *     avatar?: string
       *     // 生日，格式：yyyy-MM-dd
       *     birthday?: string
       *     // 用户编码
       *     code?: string
       *     // 最近登录时间，格式：yyyy-MM-dd HH:mm:ss
       *     lastLoginTime?: string
       *     // 昵称
       *     name?: string
       *     // 手机号
       *     phone?: string
       *     // 性别
       *     sex?: string
       *     // 账号状态
       *     state?: string
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      setSex<
        Config extends Alova2MethodConfig<_PurchaserResponseDTO_> & {
          params: {
            /**
             * sex
             */

            sex: string;
          };
        }
      >(
        config: Config
      ): Alova2Method<_PurchaserResponseDTO_, 'purchaser.setSex', Config>;
      /**
       * ---
       *
       * [POST] 修改密码
       *
       * **path:** /purchaser/update/password
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 新密码
       *   newPassword: string
       *   // 原密码
       *   oldPassword: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // [title] PurchaserResponseDTO
       *   // 当前用户响应数据
       *   data?: {
       *     // 头像地址
       *     avatar?: string
       *     // 生日，格式：yyyy-MM-dd
       *     birthday?: string
       *     // 用户编码
       *     code?: string
       *     // 最近登录时间，格式：yyyy-MM-dd HH:mm:ss
       *     lastLoginTime?: string
       *     // 昵称
       *     name?: string
       *     // 手机号
       *     phone?: string
       *     // 性别
       *     sex?: string
       *     // 账号状态
       *     state?: string
       *   }
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      updatePassword<
        Config extends Alova2MethodConfig<_PurchaserResponseDTO_> & {
          data: _DTO;
        }
      >(
        config: Config
      ): Alova2Method<_PurchaserResponseDTO_, 'purchaser.updatePassword', Config>;
      /**
       * ---
       *
       * [POST] 修改手机号
       *
       * **path:** /purchaser/updatePhone
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 验证码
       *   code?: string
       *   // 电话号码
       *   phone?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应内容
       *   data?: string
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      changePhone<
        Config extends Alova2MethodConfig<_string_> & {
          data: _4;
        }
      >(
        config: Config
      ): Alova2Method<_string_, 'purchaser.changePhone', Config>;
      /**
       * ---
       *
       * [POST] 校验旧手机号
       *
       * **path:** /purchaser/valid/updatePhone
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // 验证码
       *   code?: string
       *   // 电话号码
       *   phone?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // 响应业务码
       *   code?: number
       *   // 响应内容
       *   data?: string
       *   // 响应消息
       *   msg?: string
       * }
       * ```
       */
      validUpdatePhone<
        Config extends Alova2MethodConfig<_string_> & {
          data: _4;
        }
      >(
        config: Config
      ): Alova2Method<_string_, 'purchaser.validUpdatePhone', Config>;
    };
  }

  var Apis: Apis;
}

export {};
