/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GlobalDialog: typeof import('./../components/GlobalDialog.vue')['default']
    GlobalToast: typeof import('./../components/GlobalToast.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WdButton: typeof import('@wot-ui/ui/components/wd-button/wd-button.vue')['WdButton']
    WdCalendar: typeof import('@wot-ui/ui/components/wd-calendar/wd-calendar.vue')['WdCalendar']
    WdCascader: typeof import('@wot-ui/ui/components/wd-cascader/wd-cascader.vue')['WdCascader']
    WdCellGroup: typeof import('@wot-ui/ui/components/wd-cell-group/wd-cell-group.vue')['WdCellGroup']
    WdCheckbox: typeof import('@wot-ui/ui/components/wd-checkbox/wd-checkbox.vue')['WdCheckbox']
    WdCheckboxGroup: typeof import('@wot-ui/ui/components/wd-checkbox-group/wd-checkbox-group.vue')['WdCheckboxGroup']
    WdConfigProvider: typeof import('@wot-ui/ui/components/wd-config-provider/wd-config-provider.vue')['WdConfigProvider']
    WdDatetimePicker: typeof import('@wot-ui/ui/components/wd-datetime-picker/wd-datetime-picker.vue')['WdDatetimePicker']
    WdDialog: typeof import('@wot-ui/ui/components/wd-dialog/wd-dialog.vue')['WdDialog']
    WdForm: typeof import('@wot-ui/ui/components/wd-form/wd-form.vue')['WdForm']
    WdFormItem: typeof import('@wot-ui/ui/components/wd-form-item/wd-form-item.vue')['WdFormItem']
    WdImagePreview: typeof import('@wot-ui/ui/components/wd-image-preview/wd-image-preview.vue')['WdImagePreview']
    WdInput: typeof import('@wot-ui/ui/components/wd-input/wd-input.vue')['WdInput']
    WdInputNumber: typeof import('@wot-ui/ui/components/wd-input-number/wd-input-number.vue')['WdInputNumber']
    WdPicker: typeof import('@wot-ui/ui/components/wd-picker/wd-picker.vue')['WdPicker']
    WdQrCode: typeof import('@wot-ui/ui/components/wd-qr-code/wd-qr-code.vue')['WdQrCode']
    WdRadio: typeof import('@wot-ui/ui/components/wd-radio/wd-radio.vue')['WdRadio']
    WdRadioGroup: typeof import('@wot-ui/ui/components/wd-radio-group/wd-radio-group.vue')['WdRadioGroup']
    WdRate: typeof import('@wot-ui/ui/components/wd-rate/wd-rate.vue')['WdRate']
    WdSelectPicker: typeof import('@wot-ui/ui/components/wd-select-picker/wd-select-picker.vue')['WdSelectPicker']
    WdSlider: typeof import('@wot-ui/ui/components/wd-slider/wd-slider.vue')['WdSlider']
    WdSlideVerify: typeof import('@wot-ui/ui/components/wd-slide-verify/wd-slide-verify.vue')['WdSlideVerify']
    WdSwitch: typeof import('@wot-ui/ui/components/wd-switch/wd-switch.vue')['WdSwitch']
    WdTabbar: typeof import('@wot-ui/ui/components/wd-tabbar/wd-tabbar.vue')['WdTabbar']
    WdTabbarItem: typeof import('@wot-ui/ui/components/wd-tabbar-item/wd-tabbar-item.vue')['WdTabbarItem']
    WdTextarea: typeof import('@wot-ui/ui/components/wd-textarea/wd-textarea.vue')['WdTextarea']
    WdToast: typeof import('@wot-ui/ui/components/wd-toast/wd-toast.vue')['WdToast']
    WdUpload: typeof import('@wot-ui/ui/components/wd-upload/wd-upload.vue')['WdUpload']
  }
}

// For TSX support
declare global {
  const GlobalDialog: typeof import('./../components/GlobalDialog.vue')['default']
  const GlobalToast: typeof import('./../components/GlobalToast.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const WdButton: typeof import('@wot-ui/ui/components/wd-button/wd-button.vue')['WdButton']
  const WdCalendar: typeof import('@wot-ui/ui/components/wd-calendar/wd-calendar.vue')['WdCalendar']
  const WdCascader: typeof import('@wot-ui/ui/components/wd-cascader/wd-cascader.vue')['WdCascader']
  const WdCellGroup: typeof import('@wot-ui/ui/components/wd-cell-group/wd-cell-group.vue')['WdCellGroup']
  const WdCheckbox: typeof import('@wot-ui/ui/components/wd-checkbox/wd-checkbox.vue')['WdCheckbox']
  const WdCheckboxGroup: typeof import('@wot-ui/ui/components/wd-checkbox-group/wd-checkbox-group.vue')['WdCheckboxGroup']
  const WdConfigProvider: typeof import('@wot-ui/ui/components/wd-config-provider/wd-config-provider.vue')['WdConfigProvider']
  const WdDatetimePicker: typeof import('@wot-ui/ui/components/wd-datetime-picker/wd-datetime-picker.vue')['WdDatetimePicker']
  const WdDialog: typeof import('@wot-ui/ui/components/wd-dialog/wd-dialog.vue')['WdDialog']
  const WdForm: typeof import('@wot-ui/ui/components/wd-form/wd-form.vue')['WdForm']
  const WdFormItem: typeof import('@wot-ui/ui/components/wd-form-item/wd-form-item.vue')['WdFormItem']
  const WdImagePreview: typeof import('@wot-ui/ui/components/wd-image-preview/wd-image-preview.vue')['WdImagePreview']
  const WdInput: typeof import('@wot-ui/ui/components/wd-input/wd-input.vue')['WdInput']
  const WdInputNumber: typeof import('@wot-ui/ui/components/wd-input-number/wd-input-number.vue')['WdInputNumber']
  const WdPicker: typeof import('@wot-ui/ui/components/wd-picker/wd-picker.vue')['WdPicker']
  const WdQrCode: typeof import('@wot-ui/ui/components/wd-qr-code/wd-qr-code.vue')['WdQrCode']
  const WdRadio: typeof import('@wot-ui/ui/components/wd-radio/wd-radio.vue')['WdRadio']
  const WdRadioGroup: typeof import('@wot-ui/ui/components/wd-radio-group/wd-radio-group.vue')['WdRadioGroup']
  const WdRate: typeof import('@wot-ui/ui/components/wd-rate/wd-rate.vue')['WdRate']
  const WdSelectPicker: typeof import('@wot-ui/ui/components/wd-select-picker/wd-select-picker.vue')['WdSelectPicker']
  const WdSlider: typeof import('@wot-ui/ui/components/wd-slider/wd-slider.vue')['WdSlider']
  const WdSlideVerify: typeof import('@wot-ui/ui/components/wd-slide-verify/wd-slide-verify.vue')['WdSlideVerify']
  const WdSwitch: typeof import('@wot-ui/ui/components/wd-switch/wd-switch.vue')['WdSwitch']
  const WdTabbar: typeof import('@wot-ui/ui/components/wd-tabbar/wd-tabbar.vue')['WdTabbar']
  const WdTabbarItem: typeof import('@wot-ui/ui/components/wd-tabbar-item/wd-tabbar-item.vue')['WdTabbarItem']
  const WdTextarea: typeof import('@wot-ui/ui/components/wd-textarea/wd-textarea.vue')['WdTextarea']
  const WdToast: typeof import('@wot-ui/ui/components/wd-toast/wd-toast.vue')['WdToast']
  const WdUpload: typeof import('@wot-ui/ui/components/wd-upload/wd-upload.vue')['WdUpload']
}